### ISSUE TITLE
채널톡 버전 업 되면서 ios import 정보를 못찾고있어요.

### ISSUE THREAD

**Issue by JoengUk** [turlvo/channel_talk_flutter#1]
import ChannelIo to import ChannelIOFront
로 변경하면 정상작동되고 있어요.
변경부탁드립니다.

**Comment by turlvo** [comment]
리포팅 감사드립니다.
우선 임시방편으로 ios/Podfile의 'ChannelIOSDK' 내용을 아래와 같이 바꿔 사용부탁드립니다.

```
  pod 'ChannelIOSDK', podspec: 'https://mobile-static.channel.io/ios/9.0.1/xcframework.podspec'
```
