### ISSUE TITLE
MainActivity has leaked

### ISSUE THREAD

**Issue by choim4389** [turlvo/channel_talk_flutter#10]
`Activity io.everybike.bike.MainActivity has leaked IntentReceiver io.channel.libs.youtube.player.utils.NetworkListener@212c43a that was originally registered here. Are you missing a call to unregisterReceiver()`

백버튼으로 화면 탈출시 위와같은 warning 메세지가 확인되어 리포트합니다.

**Comment by turlvo** [comment]
io.channel.libs.youtube.player.utils.NetworkListener
이부분은 ChannelIOSDK Android library에서 해결 해줘야하는 문제로 보입니다.
(이 패키지에서 해결 할 수 없는 부분이라 클로즈하겠습니다.)
