### ISSUE TITLE
Connection Error 

### ISSUE THREAD

**Issue by hpsolver** [turlvo/channel_talk_flutter#13]
i'm getting error while calling "Channel.boot({})"

<img width="1180" alt="image" src="https://github.com/turlvo/channel_talk_flutter/assets/25339734/20f98ee8-8dd1-4182-83f6-8db2213bf33b">

**Comment by turlvo** [comment]
Like example,
you pass the parameters related to Channel talk service.

```
await ChannelTalk.boot(
        pluginKey: 'pluginKey',
        memberId: 'memberId',
        email: 'email',
        name: 'name',
        memberHash: 'memberHash',
        mobileNumber: 'mobileNumber',
        trackDefaultEvent: false,
        hidePopup: false,
        language: 'english',
    );
```

**Comment by hpsolver** [comment]
Yes i'm passing all required details ,
Like {
  "pluginKey": "xxxxxxxxxxxx",
  "email":"${Globals.firebaseUser?.email}",
  "memberId":"${Globals.firebaseUser?.uid}",
  "name": "Akshay Thakur",
  "memberHash": "2b8d587b13573009c64181b6da897b135b479a5aac611b91d94aab791363325c",
  "mobileNumber": "9816922193",
  "trackDefaultEvent": false,
  "hidePopup": false,
  "language": "english"
}
