### ISSUE TITLE
안녕하세요 이전까지 잘 사용하다가 ios 채널톡이 작동하지 않습니다

### ISSUE THREAD

**Issue by kyudongDev** [turlvo/channel_talk_flutter#14]
채널톡 2.4.0, flutter 버전 3.19.4 입니다

ios 기기는 15.8 로 테스트하긴 했으나 다른 ios 기기에서도 동작하지 않습니다.

동작 확인해보니 ChannelTalk.boot에서 false를 리턴해주는 것 같네요.  확인되실까요?

**Comment by turlvo** [comment]
안녕하세요.

확인해보니 iOS의 경우 `ChannelIOSDK` SDK가 11.6.1이 설치되고, boot fail이 발생하는 것 확인 하였습니다.
오래 관리 못해 불편을 드렸네요 ㅠㅠ

현재 플러터 패키지는 
Android의 경우는 명시적으로 `ChannelIOSDK` SDK 10.0.5 지정되어 있었는데,
iOS의 경우는 latest로 되어 있어서 문제가 발생하였습니다.

우선 빠른 해결책으로는 iOS도 Android와 동일한 `ChannelIOSDK` 버전을 사용하도록 하는 방법이 있습니다.

프로젝트 `PodFile`에 추가했던 아래의 부분을 아래와 같이 적용 후 부탁드립니다.
AS-IS
```
pod 'ChannelIOSDK', podspec: 'https://mobile-static.channel.io/ios/latest/xcframework.podspec'
```

TO-BE
```
pod 'ChannelIOSDK', podspec: 'https://mobile-static.channel.io/ios/10.0.5/xcframework.podspec'
```

최신 `ChannelIOSDK`에서 문제는 더 확인해 보겠습니다.

**Comment by turlvo** [comment]
추가 확인 사항 전달드립니다.

Flutter 버전 업 된 이후 변경된 건지 모르겠지만,
Plugin쪽에 application 핸들러에 있는 `ChannelIO.initialize(application)` 부분이 호출이 안되어서 발생한 문제입니다.

Project의 `AppDelegate.swift` 에서 호출 하도록 하면 최신 `ChannelIOSDK` 사용가능합니다.


</ios/Runner/AppDelegate.swift>
```
import UIKit
import Flutter
import ChannelIOFront


@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
      
    ChannelIO.initialize(application)

    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```

**Comment by turlvo** [comment]
추가로 Android도 ChannelIOSDK 11.5.0 사용하도록 수정 배포(2.5.0)하였습니다.
