### ISSUE TITLE
채널톡 알림 설정

### ISSUE THREAD

**Issue by ChanghyeonYoon** [turlvo/channel_talk_flutter#17]
안녕하세요.

혹시 앱이 background 상태일때 채널톡이 왔을 경우 푸시를 보내는 방법이 있을까요??
fcm과 연동이 되는지 궁금합니다!

**Comment by turlvo** [comment]
`initPushToken`  method 추가해 놓긴했는데, 실제 서비스에서 동작은 확인은 못해봤었습니다.
README와 해당 method로 확인 부탁드려도 될까요?

**Comment by ChanghyeonYoon** [comment]
저도 코드 까보니 해당 method가 있어서 initPushToken으로 fcmToken을 입력했는데 fcm으로 오지 않더라구요 ㅠㅠ
채널톡 어드민에서 등록도 했는데 안되는 것으로 보아 token 주입이 안되고 있는게 아닐까 의심됩니다!

![image](https://github.com/turlvo/channel_talk_flutter/assets/71636292/cf0a973c-cbb4-46a1-90d2-2835fcbad587)

**Comment by turlvo** [comment]
이전에 적용 했던 서비스에서는 Push 이용 했었네요.
지금은 확인해보려면 Firebase 환경구축부터 해서 확인해야해서, 조금 시간이 걸릴 것 같습니다 ㅠㅠ
(Example 앱으로만 유지보수중이라...)

**Comment by ChanghyeonYoon** [comment]
네 ㅠㅠ 저도 채널톡에 문의해서 token이 정상적으로 등록된건 맞는지 같이 확인해보겠습니다

**Comment by turlvo** [comment]
파이어베이스 메세징 환경 구축 후 안드로이드 동작 확인했습니다.
아래와 같이 작업 진행했었습니다. 

https://github.com/turlvo/channel_talk_flutter/assets/24351423/0d99df8a-a8bb-4b3f-b29e-93610b09e468

- Channel IO관련 Firebase sdk 추가
![image](https://github.com/turlvo/channel_talk_flutter/assets/24351423/ed724264-19ab-41ba-aaf8-2718f184fc31)

- AndroidManifest에 추가
<img width="856" alt="image" src="https://github.com/turlvo/channel_talk_flutter/assets/24351423/2b3f75d0-9457-458a-b290-f038d79aa36c">


- ChannelIO boot후 device의 fcm token 등록
final fcmToken = await FirebaseMessaging.instance.getToken();
await ChannelTalk.initPushToken(deviceToken: fcmToken!);

**Comment by ChanghyeonYoon** [comment]
감사합니다!! 시간되실때 가능하시다면 ios도 확인 한번 부탁드립니다!

**Comment by andrewlee1228** [comment]
채널톡의 iOS 가이드를 한번 보시길 바랍니다 ~ iOS 경우는 APNS 토큰이 필요하다고 내용이 작성되어 있습니다. 
iOS의 경우에는 FirebaseMessaging 를 통하여 apns token 도 얻을 수 있으니 해당 토큰을 사용하시면 되어요~
