### ISSUE TITLE
Web 미지원

### ISSUE THREAD

**Issue by ChanghyeonYoon** [turlvo/channel_talk_flutter#18]
안녕하세요.
저희는 Flutter로 모바일용 Web 도 대응하고 있는데
현재 해당 라이브러리로 Web까지는 지원이 안되는 듯 합니다.
```
ChannelTalk.boot: MissingPluginException(No implementation found for method boot on channel channel_talk)
```

**Comment by turlvo** [comment]
퇴근 후 개인시간에 확인해볼겠습니다.

**Comment by ChanghyeonYoon** [comment]
@turlvo 감사합니다!!

**Comment by turlvo** [comment]
@ChanghyeonYoon 

Web 지원 추가하였습니다.
추가하면서 Plugin 구조가 많이 바뀌어서 pubish는 아직입니다,

제가 API 하나 하나 android/ios/web에서 확인 하기는 했지만,
혹시 v3 branch이용해서 web 적용도 하실겸 android/ios/web 사용에 문제 없는지 확인부탁드려도 될까요?
https://github.com/turlvo/channel_talk_flutter/assets/24351423/06ceb0e9-0958-4218-9deb-70f84febf4aa

**Comment by ChanghyeonYoon** [comment]
bootForWeb method가 추가된 것으로 보이는데요,
일단 원래 기존에 있던 boot method로도 web에서 대응이 되는 듯 한데 어떤의도로 bootForWeb을 구분하셨을까요?

**Comment by turlvo** [comment]
안녕하세요.

질문 감사합니다.
Web이랑 App SDK의 BootOption 중 1/3이 차이가 있어서 나누긴 했습니다만,
어떻게 생각하시나요??

Web의 Profile도 Map으로 받고 있는데, App처럼 밖으로 끄집어 내는 것도 메일 보고 살펴보다가 생각했습니다..
(할게 많네요 ㅎㅎ)


customLauncherSelector
hideChannelButtonOnBoot
zIndex
trackUtmSource

고맙습니다.
박연호 드림

**Comment by ChanghyeonYoon** [comment]
customLauncherSelector
zIndex

위 method 같은경우 진짜 web (flutter web 말고) 에서만 사용가능한 method라서 (className이나 id로 html tag 찾기, zIndex) flutter web에서 필요없을 것 같고
hideChannelButtonOnBoot 같은경우 저희는 그냥 따로 `ChannelTalk.hideChannelButton()`를 호출하고 있어서 필요는 없었어요!
trackUtmSource랑 hideChannelButtonOnBoot 만 기존 boot에서 optional하게 추가하면 어떨까요?

저희는 boot하고 무조건 updateUser를 하고 있어서 아마 기존 boot를 써도 문제가 없었나봐요

**Comment by turlvo** [comment]
네! 
좋은 의견 감사합니다.

말씀처럼 boot 만사용해도 사용가능하니,
bootForWeb은 남겨두고 README를 통해서 기존 boot써도 된다로 하는 게 혼란을 줄일 수 있을 것 같긴합니다.

적용해 보시고 문제 있으면 알려주세요~~~
특별히 문제 없으면 며칠안으로 publish해보도록 할게요

**Comment by ChanghyeonYoon** [comment]
PlatformException(Unexpected security result code, Code: -25300, Message: The specified item could not be found in the keychain., -25300, null)

갑자기 해당 에러가 발생하고 있는 것 같아요!

**Comment by ChanghyeonYoon** [comment]
<img width="477" alt="image" src="https://github.com/turlvo/channel_talk_flutter/assets/71636292/6d8cda2a-b6f1-4167-bd5c-a19227710d30">

**Comment by turlvo** [comment]
혹시 무슨 동작하다가 나온 에러일까요?2024. 5. 13. 오후 7:32, Changhyeon (Kevin) Yoon ***@***.***> 작성:﻿
PlatformException(Unexpected security result code, Code: -25300, Message: The specified item could not be found in the keychain., -25300, null)
갑자기 해당 에러가 발생하고 있는 것 같아요!

**Comment by ChanghyeonYoon** [comment]
다른에러였습니다^^...죄송해요

**Comment by turlvo** [comment]
앗 다행이네요 ^^

처음보는 에러라 깝놀했네요

**Comment by turlvo** [comment]
혹 실례가 안된다면 어떤 서비스 만들고 계신가요??2024. 5. 13. 오후 9:59, Yeon Ho Park ***@***.***> 작성:﻿앗 다행이네요 ^^처음보는 에러라 깝놀했네요2024. 5. 13. 오후 9:47, Changhyeon (Kevin) Yoon ***@***.***> 작성:다른에러였습니다^^...죄송해요—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ChanghyeonYoon** [comment]
[그랜터](https://granter.biz) 라는 서비스를 만들고 있습니다!

**Comment by turlvo** [comment]
앗 답변 감사합니다.

이 플러그인 처음 만들때에만 해도 저도 창현님과 같은 위치였었는데요 ㅎㅎ

하시는 프로덕트에 민폐를 끼치지 않도록
이슈나 추가 구현이 필요한 부분이 있으면 최대한 대응하겠습니다.
PR로 해주시면 더 감사하고요 므흣!

마지막으로 지금 운영하시는 웹 프로덕트도 플러터로 돌아가고 있는 건가요?
(플러터 웹으로 서비스 중인곳이 있을까 해서요)

**Comment by ChanghyeonYoon** [comment]
저희는 pc는 리액트
모바일은 플러터 웹 사용 중 입니다!
m.granter.biz에요!

제가 플러터 한지 2-3달 밖에 안돼서..
더욱 증진해서 도움드릴 수 있도록 하겠습니다!
감사해요 :)

**Comment by turlvo** [comment]
모바일 웹을 플러터로 하고 계시는군요.
한번 구경해보겠습니다.

그럼 좋은밤 되세요~~~

**Comment by turlvo** [comment]
v3.0.0 으로 릴리즈하였습니다.
