### ISSUE TITLE
flutter_inappwebview를 사용중입니다. 2.x 버전과 3.0 버전에서의 차이로 인해 3.0을 사용할 수 없는데 2.x 버전이 추가로 업데이트 될 여지는 있을까요?

### ISSUE THREAD

**Issue by spanner-monkeyz** [turlvo/channel_talk_flutter#20]
현재 인앱웹뷰를 통해 서비스를 진행하고 있습니다. 
flutter_inappwebview 6.0.0 버전에서 사용되는 js 버전이 0.6.4 인 상태인데
최근 업데이트 된 channel_talk_flutter 3.0.0 버전에서는 js 버전이 0.7.1 입니다. 
뭐 결국 flutter_inappwebview 쪽에서 업데이트를 해줘야겠으나 현재 2.6.2 버전 이후로는 의존성 때문에 더 올릴 수 없는 상태라서요.
그런 상태이기때문에 현재 운영중인 2.x 버전이 추가로 업데이트 진행될 여지가 있으실지 질문드려봅니다.

**Comment by spanner-monkeyz** [comment]
dependency_overrides 로 우선 해결했습니다.

**Comment by turlvo** [comment]
안녕하세요.

불편을 드려 죄송합니다.

초기에 Web platform 지원하면서 js package를 이용했었는데,
최근에 다시 dart:js_interop으로 변경하였습니다.

변경하면서 추가해놨던 js 패키지 디펜던시를 삭제 안했네요 ^^;;;
Js dependency만 삭제하면 쉽게 해결될 것으로 보이는데 괜찮으실까요?

**Comment by spanner-monkeyz** [comment]
네네 의존도만 삭제되면 바로 반영하는데 문제 없습니다!

**Comment by spanner-monkeyz** [comment]
3.1.0 버전 업그레이드 후 이슈 없습니다. 
빠른 대응 감사드립니다!

**Comment by turlvo** [comment]
넵!

동작 이상한거 있으면 이슈 올려주시면 대응하겠습니다.
참고로 iOS ChannelIOSDK version 도 올렸기때문에 
프로젝트 Podfile도 변경해 주셔야합니다.

감사합니다
