### ISSUE TITLE
기존에 updateUser customAttributes 필드는 어떻게 마이그레이션 해야할까요?

### ISSUE THREAD

**Issue by HarryPillyze** [turlvo/channel_talk_flutter#21]
안녕하세요, 좋은 플러그인 만들어주셔서 감사합니다.

3점대로 업그레이드를 진행하고 싶은데, 마이그레이션 가이드가 없어서 문의글 남깁니다.

**Comment by turlvo** [comment]
안녕하세요.

API 문서에서 `customAttributes`가 사라져서 제거 했었는데, 
다시 살려서 확인해보니 동작하고 있어서 다시 추가했습니다.
`V3.1.1` 로 확인 부탁드립니다.

특별한 마이그레이션 가이드는 없고, README에서 아래 `ChannelIOSDK`의 version을 11.7.3 명시하는게 중요합니다.
귀찮지만  패키지의 iOS `ChannelIOSDK` 버전이 올라갈 때마다 같이 대응해 줘야합니다.
```
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  # Add below line
  pod 'ChannelIOSDK', podspec: 'https://mobile-static.channel.io/ios/11.7.3/xcframework.podspec'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```

**Comment by turlvo** [comment]
문제가 없으면 클로즈하겠습니다. 문제 발생하면 다시 오픈해주세요.

**Comment by HarryPillyze** [comment]
감사합니다 :)
