### ISSUE TITLE
12.0.0 업데이트 요청드립니다 ~

### ISSUE THREAD

**Issue by mgrv-yhlee** [turlvo/channel_talk_flutter#24]
https://developers.channel.io/docs/android-change-logs 채널톡의 큰 변화가 있었습니다. 12.0.0 업데이트 요청드려 보아요 ~ @turlvo  ~

**Comment by turlvo** [comment]
아래와 같은 변경사항으로 ChannelIOSDK 12.x 대응 하도록 3.2.0 배포하였습니다.

- Upgrade iOS's ChannelIOSdk version to 12.1.0
- Upgrade Android's ChannelIOSdk version to 12.2.0
- Added `hidePopup` API
- BREAKING: Removed `openSupportBot` and added `openWorkflow`
