### ISSUE TITLE
Pod sdk 버전 README.md 업데이트 요청

### ISSUE THREAD

**Issue by woogi-kang** [turlvo/channel_talk_flutter#27]
안녕하세요, 패키지를 잘 사용하고 있습니다.
3.3.0 업데이트 이후에 README.md에 관련 내용이 반영되지 않은 것으로 보여 업데이트 요청드립니다.
버전에 대한 명시를 업데이트해주시면 감사하겠습니다.

pod 'ChannelIOSDK', podspec: 'https://mobile-static.channel.io/ios/12.2.1/xcframework.podspec'

감사합니다.

**Comment by turlvo** [comment]
@woogi-kang 
c9af5aff9a4c04ed0155f3952587b16a5f7f57ef
Thank you!
I updated README
