### ISSUE TITLE
iOS Push 가 수신되지 않습니다

### ISSUE THREAD

**Issue by choi-bong-sik** [turlvo/channel_talk_flutter#5]
아직 프로젝트 설정 단계중 이긴 한데요,

FCM 설정을 완료 해도 iOS 단말기에서 푸시가 수신되지 않는 현상이 있습니다.

혹시 다른 설정을 해줘야 할게 있을까요?

**Comment by turlvo** [comment]
https://developers.channel.io/docs/ios-push-notification

app store push key파일을 채널톡에 등록은 하셨나요?
 그리고 기기 토큰을 initPushToken sdk로 boot 이후 호출 해주셨는지요?

**Comment by choi-bong-sik** [comment]
https://developers.channel.io/docs/ios-push-notification
app store push key파일을 채널톡에 등록은 하셨나요?
> 네 등록되어 있습니다

https://developers.channel.io/docs/ios-push-notification#register-device-token
이 부분을 flutter ios AppDelegate 관련 파일안에 swift/object-c 에 맞게 선언해 줘보시겠어요?
> 네 선언되어 있습니다
