### ISSUE TITLE
채널톡 모바일 SDK 10.0 업그레이드

### ISSUE THREAD

**Issue by i2gor87** [turlvo/channel_talk_flutter#7]
https://channelio.notion.site/SDK-71df641a09ca49c1b2f346e49301f0e3

채널톡 모바일 SDK 10.0 업그레이드되었는데 이 플로그인도 업그레이드하면 어떨 까 싶습니다.

**Comment by turlvo** [comment]
답변이 늦어져서 죄송합니다.


iOS는 아래와 같이 **latest**로 되어 있어, 'pod update'로 10.0 SDK적용이 가능합니다.
```
pod 'ChannelIOSDK', podspec: 'https://mobile-static.channel.io/ios/latest/xcframework.podspec'
```

Android의 경우 아래와 같이 'build.gradle'에 픽스되어 있어서, 옛버전이 사용되고 있었네요...
```
implementation 'io.channel:plugin-android:8.4.0'
```
수정하여 Android도 10.0 SDK 적용되도록 수정 및 Package 배포하였습니다.


> Non Null-Safety: 1.3.0
> Null-Safety: 2.2.0
